task :default => 'morning:get_ready'

namespace :morning do
  desc "Turns off the goddamn alarm."
  task :turn_off_alarm do
    puts "Turned off the alarm."
  end

  desc "Make myself pretty."
  task :groom_myself do
    puts "Brushed teeth."
    puts "Showered."
    puts "Styled beard."
  end

  desc "Correct deficiencies in my bloodstream."
  task :make_coffee do
    cups = ENV["COFFEE_CUPS"] || 2
    puts "Made #{cups} cups of coffee."
  end

  desc "I hate that little dog so much."
  task :walk_dog do
    puts "Horrible little dog walked."
  end

  desc "Ready everything for the day."
  task :get_ready => [:turn_off_alarm, :groom_myself, :make_coffee, :walk_dog] do
    puts "Face the day."
  end
end

namespace :afternoon do
  task :make_coffee do
    Rake::Task['morning:make_coffee'].invoke
    puts "Ready for the afternoon!"
  end
end


